version: '3.1'

services:
    node:
        build: 
            context: ./node 
        entrypoint: dockerize -wait tcp://db:3306 -timeout 20s node index.js
        container_name: node
        tty: true
        ports:
            - "3333:3333"
        volumes:
            - ./node:/usr/src/app
        depends_on:
            - db
        networks:
            - mynetwork
    
    nginx:
        build: 
            context: ./nginx 
        ports:
          - '8080:80' 
        container_name: nginx
        depends_on:
            - node
        networks:
            - mynetwork
    
    db:
        build: 
            context: ./mysql 
        container_name: db
        command: --innodb-use-native-aio=0
        restart: always
        tty: true
        ports:
          - '3306:3306' 
        volumes: 
            - ./data:/var/lib/mysql
        networks:
            - mynetwork

networks:
    mynetwork:
        driver: bridge