version: '3.1'

services:
    node:
        build: 
            context: ./node 
        entrypoint: dockerize -wait tcp://mysql:3306 -timeout 20s docker-entrypoint.sh
        container_name: node
        tty: true
        ports:
            - "3333:3333"
        volumes:
            - ./node:/usr/src/app
        depends_on:
            - mysql
        networks:
            - mynetwork
    
    nginx:
        build: 
            context: ./nginx 
        ports:
          - '8080:80' 
        container_name: nginx
        depends_on:
            - node
        networks:
            - mynetwork
    
    mysql:
        build: 
            context: ./mysql 
        container_name: mysql
        command: --innodb-use-native-aio=0
        restart: always
        tty: true
        ports:
          - '3006:3006' 
        volumes: 
            - ./data:/var/lib/mysql
        environment: 
            - MYSQL_DATABASE=nodedb
            - MYSQL_ROOT_PASSWORD=root
        networks:
            - mynetwork

networks:
    mynetwork:
        driver: bridge